# Generated by Django 5.2.4 on 2025-08-05 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid email address.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')], verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='contact',
            field=models.CharField(max_length=255, verbose_name='Contact (Email)'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_type',
            field=models.CharField(choices=[('email', 'Email'), ('password_reset', 'Password Reset'), ('login', 'Login'), ('register', 'Register')], max_length=20, verbose_name='OTP Type'),
        ),
    ]
