# Generated by Django 5.2.4 on 2025-08-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Session'),
        ),
    ]
