# Generated by Django 5.2.4 on 2025-08-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_is_active_to_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='device_id',
            field=models.CharField(max_length=255, verbose_name='Device ID'),
        ),
    ]
