# Generated by Django 5.2.4 on 2025-08-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_device_id_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=40, verbose_name='Session Key'),
        ),
    ]
