services:
  - type: web
    name: edvoayge
    env: python
    plan: free
    region: oregon

    # Install system dependencies here (instead of apt-get in build.sh)
    aptPackages:
      - poppler-utils
      - build-essential
      - libpq-dev

    pythonVersion: 3.13
