# Generated by Django 5.2.4 on 2025-08-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(choices=[('NEET UG 2025', 'NEET UG 2025'), ('NEET UG 2024', 'NEET UG 2024'), ('NEET UG 2023', 'NEET UG 2023'), ('NEET PG 2025', 'NEET PG 2025'), ('NEET PG 2024', 'NEET PG 2024'), ('NEET PG 2023', 'NEET PG 2023'), ('MBBS 1st Year', 'MBBS 1st Year'), ('MBBS 2nd Year', 'MBBS 2nd Year'), ('MBBS 3rd Year', 'MBBS 3rd Year'), ('MBBS 4th Year', 'MBBS 4th Year'), ('MBBS (House Surgeon)', 'MBBS (House Surgeon)'), ('MBBS PG 1st year', 'MBBS PG 1st year'), ('MBBS PG 2nd Year', 'MBBS PG 2nd Year')], default='NEET UG 2025', max_length=50, verbose_name='Year'),
        ),
    ]
