# Generated by Django 5.2.4 on 2025-09-23 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='category',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='flashcards/pdfs/'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.subject'),
        ),
    ]
