# Generated by Django 5.2.4 on 2025-09-24 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_flashcard_category_flashcard_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='notes.category'),
            preserve_default=False,
        ),
    ]
