# Generated by Django 5.2.4 on 2025-08-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Application Number'),
        ),
    ]
