# Generated by Django 5.2.4 on 2025-08-04 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='gallery',
        ),
        migrations.CreateModel(
            name='UniversityGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='universities/gallery/', verbose_name='University Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='universities/gallery/', verbose_name='University Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='universities/gallery/', verbose_name='University Image 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='universities/gallery/', verbose_name='University Image 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='universities/gallery/', verbose_name='University Image 5')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='universities/gallery/', verbose_name='University Image 6')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='universities.university')),
            ],
        ),
    ]
