# Generated by Django 5.2.4 on 2025-09-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_remove_university_gallery_universitygallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='User Name')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='feeds/profile_images/', verbose_name='Profile Image')),
                ('title', models.CharField(max_length=255, verbose_name='Heading / Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='universities.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
                'ordering': ['-created_at'],
            },
        ),
    ]
